
const URL_GET_CONTACT: string = '/contact'
const URL_GET_DEAL: string = '/deal'

interface IContact {
    "stage": string|null,
    "id": number,
    "email": string|null,
    "title": string|null
    "firstname": string|null
    "lastname": string|null
    "score": string|null
    "language": string|null
    "owner": string|null
    "ownerName": string|null
    "company": string|null
    "companyName": string|null
    "position": string|null
    "phone": string|null
    "phoneLocal": string|null
    "phoneInternational": string|null
    "mobile": string|null
    "mobileLocal": string|null
    "mobileInternational": string|null
    "fax": string|null
    "website": string|null
    "address1": string|null
    "address2": string|null
    "country": string|null
    "state": string|null
    "city": string|null
    "zip": string|null
    "facebook": string|null
    "twitter": string|null
    "skype": string|null
    "googlePlus": string|null
    "linkedin": string|null
    "instagram": string|null
    "comments": string|null
    "clientComments": string|null
    "customData": object|null,
    "membership": string|null
    "blacklist": null,
    "referredDate": null,
    "referredByContactId": null,
    "referredAtCampaignId": null,
    "referredAtInteractionId": null,
    "lastTrackingId": null,
    "lastFingerprint": null,
    "hadDuplicateDetected": false,
    "firstClickEventDate": null,
    "firstClickEventId": null,
    "firstClickEventCampaign": null,
    "lastClickEventDate": null,
    "lastClickEventId": null,
    "lastClickEventCampaign": null,
    "firstVisitEventDate": null,
    "firstVisitEventId": null,
    "firstVisitEventCampaign": null,
    "lastVisitEventDate": null,
    "lastVisitEventId": null,
    "lastVisitEventCampaign": null,
    "firstConversionEventDate": null,
    "firstConversionEventId": null,
    "firstConversionEventCampaign": null,
    "firstConversionEventUrl": null,
    "firstConversionEventContentType": null,
    "firstConversionEventContentId": null,
    "firstConversionEventVariantId": null,
    "firstConversionEventPopupId": null,
    "firstConversionEventFormId": null,
    "lastConversionEventDate": null,
    "lastConversionEventId": null,
    "lastConversionEventCampaign": null,
    "lastConversionEventUrl": null,
    "lastConversionEventContentType": null,
    "lastConversionEventContentId": null,
    "lastConversionEventVariantId": null,
    "lastConversionEventPopupId": null,
    "lastConversionEventFormId": null,
    "firstCallEventDate": null,
    "firstCallEventId": null,
    "firstCallEventCampaign": null,
    "firstCallEventCcCampaign": null,
    "firstCallEventAgent": null,
    "firstCallEventDisposition": null,
    "firstCallEventResult": null,
    "firstCallEventOutOfHour": null,
    "lastCallEventDate": null,
    "lastCallEventId": null,
    "lastCallEventCampaign": null,
    "lastCallEventCcCampaign": null,
    "lastCallEventAgent": null,
    "lastCallEventDisposition": null,
    "lastCallEventResult": null,
    "lastCallEventOutOfHour": null,
    "firstManagedCallEventDate": null,
    "firstManagedCallEventId": null,
    "firstManagedCallEventCampaign": null,
    "firstManagedCallEventCcCampaign": null,
    "firstManagedCallEventAgent": null,
    "firstManagedCallEventManagementResult": null,
    "lastManagedCallEventDate": null,
    "lastManagedCallEventId": null,
    "lastManagedCallEventCampaign": null,
    "lastManagedCallEventCcCampaign": null,
    "lastManagedCallEventAgent": null,
    "lastManagedCallEventManagementResult": null,
    "firstGoalEventDate": null,
    "firstGoalEventId": null,
    "firstGoalEventCampaign": null,
    "firstGoalEventCcCampaign": null,
    "firstGoalEventAgent": null,
    "firstGoalEventManagementResult": null,
    "lastGoalEventDate": null,
    "lastGoalEventId": null,
    "lastGoalEventCampaign": null,
    "lastGoalEventCcCampaign": null,
    "lastGoalEventAgent": null,
    "lastGoalEventManagementResult": null,
    "lastEventDate": "2022-05-24T13:56:04.223Z",
    "lastEventType": "createdDeal",
    "lastEventId": "efcced1b-4bdb-4418-ae86-bcc953a6a2d2",
    "lastEventCampaign": "",
    "createdDate": "2022-05-19T19:42:48.267Z",
    "createdOutOfHour": null,
    "createdByCampaignId": null,
    "createdByCampaignCategory": null,
    "createdByCampaignClient": "A_TEST",
    "createdByUserId": "aldo.ibarra",
    "createdByEventType": null,
    "createdByEventId": null,
    "createdBySource": "user",
    "createdBySourceId": "aldo.ibarra",
    "createdByClickSource": null,
    "createdByClickId": null,
    "createdByClickCampaign": null,
    "createdByClickAdGroup": null,
    "createdByClickKeyword": null,
    "createdByClickAdPosition": null,
    "blocked": false,
    "lastVisit": null,
    "lastConversion": null,
    "sales": null
}

interface IDeal {
    stageDescription: string;
    customData: any
}


export type {IContact, IDeal}

export {URL_GET_CONTACT, URL_GET_DEAL}
